migrated oracle to new compoundOracle
opynfinance/OptionsProtocol pull request #187
Opened 2020-10-03 05:19 UTC by mshrieve

Let me know what you think!

2020-10-03 05:28 UTC, mshrieve commented on test/oracle.test.ts
>        assert.equal(price.toString(), '2348189545860141');
I changed the decimals here on the price. I wasn't sure?

2020-10-17 01:51 UTC, mshrieve commented
this is looking pretty good now imo. lmk what you all think :)

2020-10-20 07:40 UTC, antoncoding commented on contracts/Oracle.sol
>      }
Why making btc different from other assets? 

Can't we use `getPrice(_asset)` as the main interface as well?

2020-10-20 07:43 UTC, antoncoding requested changes
As long as we're updating the oracle, I think it would be better to 
1. remove all the hardcoded address in the constructor.
2. let the admin add asset => pricer pairs. (something like `setAssetPricer(_asset, _pricer)`). So we can update the oracle used for a specific asset in the future. For now we can link all the pricer to the new compound oracle.

2020-10-20 15:07 UTC, antoncoding commented on contracts/interfaces/CompoundOracleInterface.sol
> +    function price(string calldata symbol) external view returns (uint256);
Okay this was the old interface, better update the contract address at the top of the file (`CompoundOracleInterface.sol`) (or delete it)

2020-10-20 23:23 UTC, haythem96 commented on contracts/Oracle.sol
>              return (10**18);
We are not using ETH anymore, right ? can we remove this ? // cc @aparnakr @antoncoding

2020-10-20 23:31 UTC, mshrieve commented on contracts/Oracle.sol
>      }
getPrice takes an address of a token

2020-10-20 23:32 UTC, mshrieve commented on contracts/Oracle.sol
>              return (10**18);
this is a very important feature which tells you how many wei are in 1 eth

2020-10-20 23:43 UTC, mshrieve commented on contracts/Oracle.sol
>              return (10**18);
im just kidding it should be fine to remove

2020-10-21 02:49 UTC, mshrieve commented on contracts/Oracle.sol
>              return (10**18);
actually... anyone else have thoughts on this?

2020-10-21 07:00 UTC, antoncoding commented on contracts/Oracle.sol
>              return (10**18);
we still need it in case we want to use ETH as collateral. (that part is not removed right?)

2020-10-21 07:11 UTC, mshrieve commented on contracts/Oracle.sol
>              return (10**18);
im pretty sure only OptionsContractever calls `oracle.getPrice`. and the `getPrice` of OptionsContract looks like this:

```   
function getPrice(address asset) internal view returns (uint256) {
  if (asset == address(0)) {
    return (10**18);
  } else {
    return oracle.getPrice(asset);
  } 
}

2020-10-21 07:18 UTC, mshrieve commented on contracts/Oracle.sol
>              return (10**18);
re: my stupid joke, maybe that we dont need the oracle to fetch price of eth in wei.
but maybe it makes sense to put it there as an all-in-one pricing module.
lmk if yall have thoughts

2020-10-21 07:28 UTC, antoncoding commented on contracts/Oracle.sol
>              return (10**18);
ohh now I see it. Definitely remove it 😂

2020-10-22 15:19 UTC, aparnakr approved these changes

2020-10-22 17:12 UTC, haythem96 commented on contracts/Oracle.sol
>              return (10**18);
@aparnakr thoughts ?

2020-10-22 17:12 UTC, haythem96 commented on contracts/Oracle.sol
>              return (10**18);
@antoncoding we removed ETH from V1, right ?

2020-10-22 17:17 UTC, haythem96 commented on contracts/Oracle.sol
>              return (10**18);
Oh okay I think it is better to remove the check if address equal to zero in the OptionContract.sol

2020-10-22 17:30 UTC, mshrieve commented on contracts/Oracle.sol
>              return (10**18);
ok cool so i will leave it in the oracle 👍🏻

2020-10-22 17:44 UTC, haythem96 commented on contracts/Oracle.sol
>      }
Please resolve this comment if there is no other open question.

2020-10-22 18:00 UTC, haythem96 commented
If time permit, I suggest removing all those variables as they are not needed: (the variables + their getters and setters functions)
```
        cEth = 0x4Ddc2D193948926D02f9B1fE9e1daa0718270ED5;
        cBat = 0x6C8c6b02E7b2BE14d4fA6022Dfd6d75921D90E4E;
        cDai = 0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643;
        cRep = 0x158079Ee67Fce2f58472A96584A73C7Ab9AC95c1;
        cUsdc = 0x39AA39c021dfbaE8faC545936693aC917d5E7563;
        cWbtc = 0xC11b1268C1A384e55C48c2391d8d480264A3A7F4;
        cZrx = 0xB3319f5D18Bc0D84dD1b4825Dcde5d5f7266d407;

        bat = 0x0D8775F648430679A709E98d2b0Cb6250d2887EF;
        dai = 0x6B175474E89094C44Da98b954EedeAC495271d0F;
        rep = 0x1985365e9f78359a9B6AD760e32412f4a445E862;
        usdc = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
        wbtc = 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599;
        zrx = 0xE41d2489571d322189246DaFA5ebDe1F4699F498;
```

and have them hard-coded in the constructor.

e.g:
instead of `isCtoken[cBat] = true;` => `isCtoken[0x6C8c6b02E7b2BE14d4fA6022Dfd6d75921D90E4E] = true;`

2020-10-23 01:25 UTC, mshrieve commented on contracts/Oracle.sol
>      }
this have both been removed.

2020-10-23 01:25 UTC, mshrieve commented
ok. ive  incorporated all the changes we discussed!

2020-10-23 01:50 UTC, antoncoding commented
> If time permit, I suggest removing all those variables as they are not needed: (the variables + their getters and setters functions)
> 
> ```
>         cEth = 0x4Ddc2D193948926D02f9B1fE9e1daa0718270ED5;
>         cBat = 0x6C8c6b02E7b2BE14d4fA6022Dfd6d75921D90E4E;
>         cDai = 0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643;
>         cRep = 0x158079Ee67Fce2f58472A96584A73C7Ab9AC95c1;
>         cUsdc = 0x39AA39c021dfbaE8faC545936693aC917d5E7563;
>         cWbtc = 0xC11b1268C1A384e55C48c2391d8d480264A3A7F4;
>         cZrx = 0xB3319f5D18Bc0D84dD1b4825Dcde5d5f7266d407;
> 
>         bat = 0x0D8775F648430679A709E98d2b0Cb6250d2887EF;
>         dai = 0x6B175474E89094C44Da98b954EedeAC495271d0F;
>         rep = 0x1985365e9f78359a9B6AD760e32412f4a445E862;
>         usdc = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
>         wbtc = 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599;
>         zrx = 0xE41d2489571d322189246DaFA5ebDe1F4699F498;
> ```
> 
> and have them hard-coded in the constructor.
> 
> e.g:
> instead of `isCtoken[cBat] = true;` => `isCtoken[0x6C8c6b02E7b2BE14d4fA6022Dfd6d75921D90E4E] = true;`

This is already an Ownable contract, can we just have a ownerOnly function that can set isCtoken = true, and remove all the hardcoded addresses in the constructor? 

```javascript
function setIsCToken(address _token, bool _isCToken) onlyOwer external {
   isCtoken[_token] = _isCToken;
}
```

2020-10-23 01:51 UTC, antoncoding commented on contracts/Oracle.sol
> +    }
we don't need this as well

2020-10-23 02:06 UTC, mshrieve commented on contracts/Oracle.sol
> +    }
removed

2020-10-23 02:29 UTC, mshrieve commented
re: anton's comment, I removed hard-coded address

2020-10-23 06:57 UTC, antoncoding approved these changes

2020-10-23 13:25 UTC, haythem96 approved these changes
LGTM

2020-10-23 13:26 UTC, merged